### PR TITLE
update New Relic JS snippet to v1209

### PR DESCRIPTION
**Pull request by robrap**
Updated New Relic JS snippet to v1209. See:
https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1209/

Additionally, a changelog was introduced to make it easier to find and read about breaking changes.

### CODE REVIEW

**Comment by robrap** [comment]
@victorrodrigues: I will be testing locally, but it would be great to get this upgrade. Thank you.

**Comment by robrap** [comment]
**UPDATE**: @victorrodrigues: I have tested locally and seems to work fine.

**Comment by victorrodrigues** [comment]
@robrap Thanks again for the contribution! It was already published.

**Comment by robrap** [comment]
Thanks @victorrodrigues.

**Pull request merged**
