### PR TITLE
update NewRelic Browser snippet to v1184

### PR DESCRIPTION
**Pull request by robrap**
Updates New Relic JS snippet from v1118 to v1184. See [New Relic release notes](https://docs.newrelic.com/docs/release-notes/new-relic-browser-release-notes/browser-agent-release-notes/browser-agent-v1184
). 
 
**BREAKING CHANGE:** The latest New Relic scripts require the
following additional data: accountID, agentID and trustKey.
See the README.md for tips gathering this data from the
snippet in the New Relic UI.

The new `trustKey` should match across your New Relic applications (at least within an account), but the `agentID` looks to be different for each application.

The plugin uses the snippet for Pro+SPA instrumentation. This
snippet will work for Pro instrumentation, but SPA data will
be dropped by New Relic until Pro+SPA instrumentation is ever
selected.

### CODE REVIEW

**Comment by robrap** [comment]
@victorrodrigues: FYI: This has only been tested via unit tests at this point.

**Comment by robrap** [comment]
@victorrodrigues: FYI: I'm working on this update PR on this fork instead: https://github.com/edx/html-webpack-new-relic-plugin/pull/3.  I will get it tested, but this may take some time.  If I don't hear back from you by the time it is ready, we'll likely permanently switch to our fork.  I hope things are going well for you.  Thank you again for getting this work started.

**Comment by victorrodrigues** [comment]
Sorry for the delayed response @robrap, I was busy as hell.
But it was published as v3.0.0, ok? Let me know if it was ok.

**Comment by robrap** [comment]
Thanks @victorrodrigues. Will do. I was considering renaming another option, discussed here: https://github.com/edx/html-webpack-new-relic-plugin/pull/3#discussion_r554226953
I could do that as a quick 4.0.0 follow-up, or we can forget about it for now. Let me know your thoughts.

**Pull request merged**
