### PR TITLE
Update NewRelic Browser snippet.

### PR DESCRIPTION
**Pull request by robrap**
This updated snippet supports customAttributes on the
newrelic.noticeError call.

### CODE REVIEW

**Comment by robrap** [comment]
Oops.  I meant to create this PR on my fork only.  I will close this for now and let you know when this is tested.  Thanks.

**Comment by robrap** [comment]
@victorrodrigues: I now tested this sending `customAttributes` to` newrelic.noticeError()`, and the updated snippet works as expected.  Thanks for the plugin!

**Comment by robrap** [comment]
FYI: This updates to snippet v1118 as seen in `agent:"js-agent.newrelic.com/nr-spa-1118.min.js"`.

**Comment by victorrodrigues** [comment]
Sorry for the response delay @robrap. It was merged and published as 1.1.0.
Thanks for the contribution! 👍

**Comment by robrap** [comment]
Thanks @victorrodrigues.  I was just about to create my own repo, so your merge helped me out.

**Pull request merged**
